//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddToComputersDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memories
    {
        public int id { get; set; }
        public int capacity { get; set; }
        public string type { get; set; }
        public string manufcator { get; set; }
        public bool computerType { get; set; }
        public Nullable<bool> freeToUse { get; set; }
    
        public virtual MotherBoard motherBoard { get; set; }

        public int speed
        {
            get => default(int);
            set
            {
            }
        }
    }
}
