//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddToComputersDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MotherBoard()
        {
            this.MobosSockets = new HashSet<MobosSockets>();
            this.Disks = new HashSet<Disks>();
            this.Memories = new HashSet<Memories>();
        }
    
        public int id { get; set; }
        public string manufcator { get; set; }
        public string model { get; set; }
        public Nullable<int> slots { get; set; }
        public Nullable<int> Channels { get; set; }
        public string memoryType { get; set; }
        public Nullable<int> memoryMaxSize { get; set; }
        public Nullable<bool> computerType { get; set; }
        public Nullable<int> proessorID { get; set; }
        public Nullable<int> computerID { get; set; }
        public Nullable<int> SataConnectors { get; set; }
        public Nullable<bool> architacture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobosSockets> MobosSockets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disks> Disks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memories> Memories { get; set; }
        public virtual Processors Processors { get; set; }
        public virtual Computers Computers { get; set; }
    }
}
