//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddToComputersDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Processors()
        {
            this.ProcessorSocket = new HashSet<ProcessorSocket>();
            this.MoBos = new HashSet<MoBos>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> generation { get; set; }
        public string family { get; set; }
        public Nullable<int> speed { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<bool> architacture { get; set; }
        public Nullable<bool> freeToUse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessorSocket> ProcessorSocket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoBos> MoBos { get; set; }
    }
}
